### ISSUE TITLE
Huginn agent for parsing Aftership tracking updates

### ISSUE THREAD

**Issue by negebauer** [negebauer/huginn-javascript-agents#1]

**Comment by negebauer** [comment]
- [ ] Location should be empty if no location. Also with a br. Now it’s showing null
- [ ] Use tag and message. Tag first with the date and then the message
- [ ] Use last checkpoint (or tag, subtag) for deciding to send email again
